### ISSUE TITLE
Exception when user cancels file selection

### ISSUE THREAD

**Issue by skliche** [skliche/request-metrics-analyzer-next#2]
When a user hits the cancel button when opening a file an exception occurs in the SystemOut log:

```
java.io.FileNotFoundException: nullnull (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileReader.<init>(FileReader.java:72)
    at de.ibm.issw.requestmetrics.engine.RmProcessor.processInputFile(RmProcessor.java:51)
    at de.ibm.issw.requestmetrics.engine.RmProcessor.processInputFile(RmProcessor.java:44)
    at de.ibm.issw.requestmetrics.gui.RequestMetricsGui$1.actionPerformed(RequestMetricsGui.java:95)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
```

**Comment by skliche** [comment]
Fixed in c602e1694b2d214d01b85942a141dfad919d4f42
